version: '3'
services:
    db:
        image: postgres:11.4-alpine
        container_name: postgres
        ports: 
            - 5442:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: simalend
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
    alembic:
        build: .
        container_name: alembic
        links:
            - db
        environment:
            POSTGRES_HOST: postgresql://admin:admin@db:5432/simalend
        command: alembic upgrade head
        restart: on-failure
    app:
        extra_hosts:
            - "somehost:127.0.0.1"
        build: .
        container_name: application
        ports:
            - "3000:3000"
        links:
            - db
        environment:
            POSTGRES_HOST: postgresql://admin:admin@db:5432/simalend
        entrypoints:
            
        restart: always