swagger: "2.0"
info:
  title: Sample API
  description: Easy sample API CRUD
  version: 0.0.1
  contact:
    name: api support
    email: example@mail.com

schemes:
  - http
paths:
  /api/v1/create:
    get:
      summary: info create user
      tags:
      - CRUD
      description: Creating a user and their rights
      parameters:
        - in: query
          name: first_name
          required: true
          description: First name user
          schema:
            type: string
        - in: query
          name: last_name
          description: Last name user
          required: true
          schema:
            type: string
        - in: query
          name: login
          required: true
          description: login user
          schema:
            type: string
        - in: query
          name: password
          description: password user
          required: true
          schema:
            type: string
        - in: query
          name: date_birth
          required: true
          description: date birth user
          schema:
            type: string
        - in: query
          name: permission
          description: permission user
          required: true
          schema:
            type: string
  /api/v1/delete:
    get:
      summary: info delete user
      tags:
      - CRUD
      description: find a user by login and delete it
      parameters:
        - in: query
          name: login
          required: true
          description: login
          schema:
            type: string
  /api/v1/read:
    get:
      summary: info read users
      tags:
      - CRUD
      description: Will find all users by limit (latest entries)
      parameters:
        - in: query
          name: limit
          required: true
          description: number of recent entries
          schema:
            type: string
  /api/v1/update:
    get:
      summary: info update users
      tags:
      - CRUD
      description: Update user by login
      parameters:
        - in: query
          name: first_name
          required: true
          description: First name user
          schema:
            type: string
        - in: query
          name: last_name
          description: Last name user
          required: true
          schema:
            type: string
        - in: query
          name: login
          required: true
          description: login user
          schema:
            type: string
        - in: query
          name: password
          description: password user
          required: true
          schema:
            type: string
        - in: query
          name: date_birth
          required: true
          description: date birth user
          schema:
            type: string
        - in: query
          name: permission
          description: permission user
          required: true
          schema:
            type: string
